name: Ubuntu

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  Clang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, RelWithDebInfo, MinSizeRel, Release] 
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up GCC on Ubuntu
        run: |
          sudo apt-get install -y gcc-11

      - name: cmake
        run: cmake -S . -B build
      - name: build
        run: cmake --build build --config=${{ matrix.build_type }}


  GCC:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, RelWithDebInfo, MinSizeRel, Release] 

    steps:
      - uses: actions/checkout@v2
      - name: Set up Clang on Ubuntu
        run: |
          sudo apt-get install -y clang-10

      - name: CMake
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=clang-10

      - name: Build
        run: cmake --build build --config=${{ matrix.build_type }}
